### ISSUE TITLE
Unable to find the type for stream "image". It may be set to AnyType or something else that isn't determinable,

### ISSUE THREAD

**Issue by LizbethShaji** [lanzani/jetson-libraries#1]
I was able to successfully install Mediapipe version 0.10.7 using [mediapipe-0.10.7-cp38-cp38-linux_aarch64.whl](https://github.com/lanzani/jetson-libraries/raw/main/libraries/mediapipe/l4t32.7.1/py3.8.0/mp0.10.7/mediapipe-0.10.7-cp38-cp38-linux_aarch64.whl) for GPU utilization, but while trying to run the sample code provided in [test script](https://jetson-docs.com/libraries/mediapipe/overview#test-gpu-support), I am encountering the following error :- "**Unable to find the type for stream 'image'. It may be set to AnyType or something else that isn't determinable**". 
Note:- I intend to use Mediapipe for hand tracking.

**Comment by lanzani** [comment]
Hello!
1. Are you usign the test script for mediapipe 0.10.x? ([this one](https://jetson-docs.com/libraries/mediapipe/overview#mediapipe-0-10-x))
2. If you run that script "as-it-is" with the "pose_landmarker_full.task" it works, or it gives you the same problem?

**Comment by LizbethShaji** [comment]
@lanzani 
Thank you for your suggestion! I tested the [test script](https://jetson-docs.com/libraries/mediapipe/overview#mediapipe-0-10-x) using pose_landmarker_full.task, and it resolved the issue I was facing.
Just to clarify, is there any other solution without having to use base_options in every code. 

Thanks again for your help!

**Comment by lanzani** [comment]
You're welcome! 

I think base_options is required.

**Comment by LizbethShaji** [comment]
Thank you for the quick response. I am closing the issue as it was resolved.
